[build]
  base = "client"
  command = "npm run build"
  publish = "dist/ng-music-flow/browser"

[functions] 
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/music/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

## ANGULAR_CHUNKS_START
[[headers]]
  for = "/*"
  [headers.values]
    Link = "</chunk-YIM5MZ47.js>; rel=modulepreload, </chunk-AQDT5OLB.js>; rel=modulepreload, </chunk-Q2C3W4U3.js>; rel=modulepreload, </chunk-HFTCX46V.js>; rel=modulepreload, </chunk-2BA2LHR4.js>; rel=modulepreload, </chunk-6YRLWLB2.js>; rel=modulepreload, </chunk-NFA5YEOO.js>; rel=modulepreload, </chunk-YCPHEWFD.js>; rel=modulepreload, </chunk-56ZFOE6B.js>; rel=modulepreload, </chunk-YFZYWRRL.js>; rel=modulepreload"
## ANGULAR_CHUNKS_END
