name: Auto Re-request Review

on:
  pull_request:
    types: [synchronize]

jobs:
  rerequest:
    runs-on: ubuntu-latest
    steps:
      - name: Re-request review
        uses: necojack/re-request-review@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}